TalkHeal.py, components/sidebar.py
- Added section linking to verified quizzes (GAD-7, PHQ-9, WHO-5, DASS)
- Included interpretation info for each score
- Fixed Streamlit expander nesting issue
=> Add quiz section and fix expander issue

README.md
Fixes: #102 
This PR adds a "📁 Project Structure" section to the README.md file to help users and contributors better understand the organization of files and directories in the repository.
🔘 Offer a visual representation of the repo layout to aid new contributors in navigating the project faster.
🔘 Reduce onboarding time for developers by making it clear where specific functionality or files are located, which helps prevent confusion when working with the codebase.
🔘 Help contributors understand the purpose of the different files and directories at a glance, making the project more accessible for those unfamiliar with the structure.
While this may have been addressed elsewhere, having a concise project structure section directly in the README helps centralize the information and ensures …
=> Update readme by adding Project Structure(#102)

components/sidebar.py
- Closes #122 
Added Calming sound section in the sidebar
yes , locally 
yes
=> Ambient Music Feature

TalkHeal.py, pages/WellnessResourceHub.py
This PR introduces a new Wellness Resource Hub to the TalkHeal app. The hub is designed to provide users with simple, practical wellness tips across different categories, helping them build healthy daily habits for better mental and physical well-being.
Features
Mind
Quick meditation practices
Journaling prompts
Mindfulness app recommendations (Headspace, Calm)
1.Body
- Short walks after meals
- Hydration reminders
- Hourly stretching tips
2.Nutrition
- Eat fresh fruits & veggies
-Reduce processed foods
- Practice mindful eating
3. Sleep
- Maintain consistent sleep schedule
- Reduce screen time before bed
- Calming routines (like herbal tea)
Screenshots
Issue Reference:
Fixes #135
Let me know if further changes required. I will be happy to improve it
=> Added WellnessResourceHub

CODE_OF_CONDUCT.md
This update refreshes the Code of Conduct to make it more welcoming, engaging, and easy to read for contributors.
- Added relevant GIFs before major sections to create a friendly and inviting tone.
- Introduced badges/icons for quick recognition of core values (✅ Respect, 🚫 No Harassment, 🌍 Inclusivity).
- Incorporated emojis throughout to make the text more approachable and scannable.
- Improved formatting, spacing, and section structure for better readability.
- Reinforced inclusivity and a positive community culture.
This change aims to improve contributor experience and make community guidelines clearer and more accessible.
=> docs: Revamp Code of Conduct with visuals, badges, and improved formatting

TalkHeal.py, components/chat_interface.py, components/sidebar.py, pages/Pinned_msg.py
- Closes #132 
Added functionality to pin/unpin messages directly from chat.
Created a Pinned Messages page displaying all pinned messages for the user.
Updated UI components to reflect pinned/unpinned status.
Updated backend logic for storing and retrieving pinned messages.
Used database tables/fields to track pinned messages for each user.
Updated API endpoints to fetch and update pinned status.
UI components dynamically show pinned messages without page reload.
Any feedback or suggestions would be greatly appreciated! I’m happy to make improvements or adjustments based on your recommendations.
Streamlit Cloud Deployment Link - https://talkheal-nikitagrover.streamlit.app/
---
=> feat: add pin/unpin messages in chat and pinned messages page

TalkHeal.py, components/chat_interface.py, components/sidebar.py, core/config.py
- TalkHeal.py: remove unused genai import; remove duplicate core.utils import
- components/sidebar.py: remove unused webbrowser, get_current_time, duplicate datetime, unused initialize_profile_state
- components/chat_interface.py: remove unused set_user_time_in_session function and commented call
- core/config.py: properly import google.generativeai.types and update except blocks
- App runs: streamlit run TalkHeal.py
- Basic chat flow works
- No linter issues
=> chore: clean imports and minor dead code removal (#153)

TalkHeal.py, components/footer.py, pages/AppOverview.py, pages/Blog.py, pages/Careers.py, pages/Community.py, pages/ContactUs.py, pages/CookiePolicy.py, pages/CopyrightNotice.py, pages/Disclaimer.py, pages/FAQs.py, pages/HelpCenter.py, pages/NewsletterSignup.py, pages/PrivacyPolicy.py, pages/SocialMedia.py, pages/TermsOfService.py
Added a privacy policy page to the footer
=> Added privacy policy page

pages/TermsOfService.py
Added terms of service page to the footer
=> Add styled Terms of Service page

pages/Disclaimer.py, pages/TermsOfService.py
=> Disclaimer page

pages/CopyrightNotice.py
Added a copyright page at the footer
=> Add styled Copyright Notice page

pages/Careers.py
Added a career page in the footer kindly check sir @eccentriccoder01
=> Added career page in the footer

pages/HelpCenter.py
=> Added help center page

pages/Community.py, pages/HelpCenter.py
Added a community page at the footer
=> Added a community page

pages/AppOverview.py, pages/Blog.py
* Closes #206
The sections on the **Blog Page** was unreadable because:
* The HTML structure was invalid (`<ul>` placed inside a `<p>` tag).
* The text color blended with the background, reducing contrast.
This fix ensures proper rendering, accessibility, and consistent readability across all environments (light and dark themes).
* Replaced `<p>` with `<div>` for valid semantic HTML structure.
* Updated text color to **black** for consistent readability.
* Confirmed that layout, spacing, and design remain intact across supported browsers.
* HTML structure corrected (`<div>` > `<ul>`).
* CSS updated with `color: black;`.
* No dependencies added or removed.
* No performance impact.
* Verified text is visible on **both light and dark modes** in Streamlit.
* Confirmed no invalid nesting …
=> style: change p tag to div for better styling control in blog page

components/login_page.py
This PR introduces a "Login as Guest" feature to the authentication page. This allows new users to explore and demo the application without needing to create an account first, lowering the barrier to entry and improving the first-time user experience.
@eccentriccoder01 
- Added a "Login as Guest" button to the login UI in `components/login_page.py`.
- Implemented the logic to bypass authentication and create a temporary "Guest Healer" session when the button is clicked.
- Also added a placeholder UI button for "Continue with Google" for potential future implementation.
1. Run the application locally.
2. On the login screen, click the "Login as Guest" button.
3. Verify that you are successfully logged in and taken to the main application dashboard.
=> feat: Add Guest Login functionality

pages/Community.py, pages/FAQs.py, pages/HelpCenter.py, pages/QnA.py, pages/SocialMedia.py
Fixes #180. This PR implements the Expert-Led Q&A Sessions page, providing users with access to content from mental health professionals. It also includes a fix for dark mode rendering to ensure readability.
=> feat: Implement Expert-Led Q&A Sessions

components/chat_interface.py, core/utils.py, setup_database.py
closes #162 
Streamlit link of my forked repo: https://talkheal-nayna.streamlit.app/
**Summary of Changes**
`components/chat_interface.py`
Added 👍/👎 feedback buttons directly under each AI chatbot message for message-level feedback.
Implemented the interactive feedback UI flow including submission, confirmation, and optional comments for negative feedback.
Added custom CSS (inject_feedback_css) for styling feedback buttons inline with chat messages.
Integrated loading of existing feedback to retain user selections after refresh or logout.
`core/utils.py`
Added functions to save feedback (save_feedback) and retrieve feedback (get_feedback), storing data in a SQLite database.
Implemented user identification by hashing email (or fallback IP) for privacy and consistent feedback tracking. …
=> [FEATURE] Add Feedback Buttons for Chatbot Responses #162

pages/Habit_Builder.py
---
This commit introduces a comprehensive habit tracking application with:
* ✅ Habit management (add, edit, complete, archive)
* ✅ Daily challenges with points system
* ✅ Progress analytics and visualizations
* ✅ Achievement badges and stats tracking
* ✅ Responsive UI with multiple tabs and sidebar
---
Closes #175
---
Tracking and building habits is a critical part of mental wellness. This feature provides users with an interactive, gamified way to stay consistent and motivated. It aligns with TalkHeal’s goal of offering practical tools beyond journaling and resources.
---
* Added **Habit\_Builder.py** under `pages/` for the habit tracking module.
* Implemented **habit CRUD (Create, Read, Update, Delete)** with completion + archive options.
* Introduced **daily challenges** with points …
=> feat: add Habit Builder Pro application with tracking and analytics

TalkHeal.py, app.py, components/sidebar.py, pages/AppOverview.py, pages/CommunityForum.py
Added a community forum page on the slider
=> Community forum

TalkHeal.py, components/login_page.py, core/utils.py, pages/Journaling.py
streamlit repo link:  https://talkheal-nayna.streamlit.app/
SUMMARY OF CHANGES:
`TalkHeal.py`: Updated the main app to handle logout more securely and ensure consistent authentication checks.
`components/login_page.py`: Modified the login process to store all user info in one clean object, making it easier to access and manage.
`core/utils.py`: Added new functions to centralize all authentication logic, making the code cleaner and more reusable.
`pages/Journaling.py`: Fixed the bug by using the new, centralized authentication functions to correctly identify the user and display their journal entries.
screenshot:
=> User Authentication Lost on Page Navigation in Journaling Section #170

pages/selfHelpTools.py
Changes were made in the links that were not visible earlier because of the background colour
Tests are done.
=> Changes made in the Visibility of Links in the knowledge section 

TalkHeal.py, components/games.py, core/utils.py, css/styles.py
Added readability on narrow screen !!!!!
=> Added readability on narrow screen

TalkHeal.py
Added 2 more cards wellness resource hub and habit builder
=> added 2 more cards wellness resource hub and habit builder

TalkHeal.py
Added 5 cards per row added Qna and community forum
=> Added 5 cards per row

TalkHeal.py, css/styles.py
=> added borders

pages/doctor_spec.py
Replace dataframe with expandable sections for each disease to enhance readability and user experience
It fixes #263
=> feat(doctor_spec): improve disease prediction results display

pages/ContactUs.py, pages/doctor_spec.py
- Replace static contact info with an interactive form for better user engagement
- Move CSS styles to a dedicated style block for better maintainability
- Improve layout and spacing of contact information
It fixes #262
=> Add interactive form and improve styling in contact page

pages/CopyrightNotice.py
- Separate CSS into dedicated styles for better maintainability
- Use semantic HTML classes and add mailto link
- Improve readability with better line spacing and color contrast
- Rename show() to render_page() for clarity
It fixes #275
=> Improve Copy Right Notice Page styling and structure

pages/NewsletterSignup.py, pages/selfHelpTools.py
- Add email validation using regex pattern
- Implement session state to prevent duplicate submissions
- Update UI text and styling for better user experience
- Add success animation and navigation option
It fixes #279
=> feat(newsletter): improve signup form with email validation and session state

pages/Community.py, pages/CommunityForum.py, pages/NewsletterSignup.py, pages/selfHelpTools.py
Add expandable forum guidelines section to inform users about community rules and expectations
It fixes #281
=> feat(CommunityForum): add forum guidelines expander section

pages/CommunityForum.py
This PR implements the v2 version of the **Community Forum** tool (`pages/Community_Forum.py`), addressing the limitations of v1 and introducing key enhancements for functionality, interactivity, and safety.
* **Post Storage & Display**
* Added `st.session_state.posts` to store posts and replies in memory.
* Posts now display with author names, timestamps, and relative "time ago" format.
* **Reply System**
* Threaded replies supported via expandable reply forms.
* Replies include avatars, author identity, and timestamps for context.
* **Basic AI Moderation**
* Implemented a profanity filter (`contains_profanity`) to block inappropriate content.
* Error message displayed for blocked posts.
* **UI/UX Improvements**
* Two-column layout (posts on left, post creation form on right).
* Modern …
=> Enhance Community Forum with Post Storage, Replies, and Moderation (Fixes #291)

pages/Blog.py, pages/Breathing_Exercise.py, pages/CommunityForum.py
This PR upgrades the **`pages/Breathing_Exercise.py`** tool by introducing selectable breathing techniques, providing users with a more personalized and engaging experience.
* **Selectable Breathing Techniques**
* Added a dropdown menu on the setup screen to choose from multiple evidence-based breathing patterns:
* **Default Relaxation (4-2-4)** – Balanced for general relaxation.
* **Box Breathing (4-4-4-4)** – Structured for focus and calm.
* **4-7-8 Breathing** – Promotes deep relaxation and sleep.
* Enables users to tailor their practice to specific goals.
* **Dynamic Animation and Guidance**
* CSS animation and text prompts now adjust dynamically to match the selected breathing pattern.
* Visual breathing guide stays synchronized with timing, offering a seamless and intuitive …
=> Enhance Breathing Exercise with Selectable Techniques (Fixes #289)

pages/Breathing_Exercise.py
This PR upgrades the **Breathing Exercise tool (`pages/Breathing_Exercise.py`)** by replacing the existing CSS-based animation with a **Lottie animation**. The goal is to enhance the visual polish, improve user engagement, and simplify the codebase.
* 🔄 **Replaced CSS animation with Lottie**
* Removed the custom `generate_animation_css` function and all dynamic CSS styling.
* Integrated `streamlit-lottie` to render `assets/yoga_animation.json`.
* Achieves smoother, professional-grade visuals for the breathing guide.
* 🧹 **Codebase Simplification**
* Eliminated redundant CSS code.
* Refactored to reduce complexity and improve maintainability.
* 🎨 **Improved User Experience**
* Visuals are now cleaner and more engaging.
* Text prompts (“Breathe In”, “Hold”, “Breathe Out”) remain intact to …
=> Upgrade Breathing Exercise: Replace CSS Animation with Lottie for Modern UX

pages/Blog.py, pages/WellnessResourceHub.py
This PR addresses **Issue #302** by upgrading the Mood Tracker in `pages/WellnessResourceHub.py` with new features and UI improvements to make it a more practical tool for self-reflection.
* **Added Notes Feature:** Users can now add optional text notes to mood entries to provide context.
* **Upgraded Data Storage:** Each mood entry is now stored as a dictionary containing both `mood` and `note`.
* **Improved UI:**
* Mood history displays both mood and note.
* Entries are listed in reverse chronological order (newest first).
* **Added Data Migration:** Legacy string-only entries are automatically migrated to the new dictionary format to ensure backward compatibility.
* Provides richer insights by capturing context behind moods.
* Improves readability and relevance of mood history.
* …
=> Enhance Mood Tracker with Notes and Improved UI

pages/Blog.py, pages/WellnessResourceHub.py
This PR resolves **Issue #308** by introducing a session-based comments section to the blog post page (`pages/Blog.py`), making the blog more interactive and engaging.
* **View Comments:** Added a comments list at the bottom of each article where users can see existing comments.
* **Add Comments:** Implemented a form for users to enter their name and comment.
* **Session-Based Storage:** Comments are stored in `st.session_state`, ensuring they persist during the session.
* This is a **foundational, non-persistent implementation**. Comments are cleared once the session ends.
* Future improvements could include database integration to enable persistent comments.
* Adds interactivity to blog posts, fostering user engagement.
* Provides the foundation for future enhancements such as …
=> Feature: Add Comments Section to Blog Posts

pages/WellnessResourceHub.py, pages/selfHelpTools.py
This PR expands the **affirmations list** in `pages/WellnessResourceHub.py` by adding several new items to make the user experience more dynamic and engaging.  
- Added multiple new affirmations to the existing list.  
- Improved diversity of content to provide broader emotional support and motivation.  
- Expand the `wellness_tasks` list.  
- Enhance the `categories` dictionary for better content categorization.  
Closes #336
=> feat: expand affirmations list in WellnessResourceHub (#336)

pages/WellnessResourceHub.py, pages/selfHelpTools.py
This PR updates and expands the **`wellness_tasks` list** in `pages/WellnessResourceHub.py` to provide users with a richer variety of suggested activities for the Daily Planner.  
- Added new wellness tasks covering mindfulness, self-care, and productivity.  
- Enhanced task diversity to keep users motivated and engaged.  
- Continue enriching the list with seasonal or themed tasks.  
- Explore categorization of tasks for easier filtering in the UI.  
Closes #337
=> feat: expand wellness_tasks list in WellnessResourceHub (#337)

pages/water_tracker_app.py
- Closes #311
This change introduces a new "Water Tracker" feature to the application. The primary goal is to enhance user engagement and provide a practical tool for daily wellness monitoring, which aligns with the app's core mission of promoting mental and physical health. By allowing users to log and track their water intake, we provide a tangible way for them to practice self-care and build healthy habits directly within the TalkHeal ecosystem.
🎯 Rationale
This change introduces a new "Water Tracker" feature to the application. The primary goal is to enhance user engagement and provide a practical tool for daily wellness monitoring, which aligns with the app's core mission of promoting mental and physical health. By allowing users to log and track their water intake, we provide a …
=> Water tracker app

pages/WellnessResourceHub.py
This PR implements a **progress bar** for the **Daily Planner** section of the Wellness Resource Hub, addressing issue **#339**.
* Added a progress bar above the task list in `pages/WellnessResourceHub.py`.
* Progress bar visually represents the ratio of completed tasks to total tasks.
* Added task completion count display (e.g., `3/5 Tasks Completed`).
* Enhances user experience by providing immediate feedback on productivity and motivation.
Closes #339
=> Feat: Add progress bar to Daily Planner in Wellness Resource Hub (#339)

pages/WellnessResourceHub.py
This PR refactors the **Wellness Resources** page (`pages/WellnessResourceHub.py`) to enhance the UI/UX by moving away from a plain markdown list and introducing a structured, modern card-based design.
* 🔹 Replaced the plain markdown list of resources with **card-based containers** for improved readability.
* 🔹 Introduced a **list of dictionaries** structure for resource data, making it easier to maintain and extend.
* 🔹 Implemented a **two-column grid layout** for better alignment and visual appeal.
* 🔹 Established a **cleaner and more organized design**, paving the way for upcoming features like resource filtering and user ratings.
This change improves the overall user experience and creates a more scalable foundation for future enhancements to the **Wellness Resources Hub**.
Closes …
=> Refactor Wellness Resources Page with Card-Based UI (#353)

pages/WellnessResourceHub.py
This PR introduces a **filtering feature** on the **Wellness Resources** page (`pages/WellnessResourceHub.py`) to enhance usability and improve the overall user experience.
* 🔹 Added a **multi-select dropdown** at the top of the page.
* 🔹 Users can now **filter resources by one or more categories**.
* 🔹 If no category is selected, the page **displays all resources by default**.
* 🔹 Ensures smoother navigation and quicker access to relevant content.
Previously, users had to scroll through all resources without any way to filter by category. With this feature, they can now directly focus on the resources that matter to them, making the page more interactive and user-friendly.
Closes #354
=> Feature: Implement Filtering for Wellness Resources (#354)

pages/WellnessResourceHub.py
This PR introduces a new **Community Tips & Stories** page to the **Wellness Hub** (`pages/WellnessResourceHub.py`) to foster engagement and provide users with encouraging, real-life insights.
* 🤝 Added **"Community Tips"** as a new menu item in the main sidebar.
* 🤝 Introduced a **card-based layout** to display tips and stories in a clean and organized format.
* 🤝 Each card contains:
* **Category** (e.g., Stress Management, Healthy Habits)
* **Story/Tip content**
* **Anonymous author attribution**
* 🤝 Initial implementation uses **hardcoded content**, which can later be expanded to pull from a **database or shared file** for dynamic updates.
* 🤝 Page designed to provide **encouragement and practical wellness advice** while maintaining simplicity.
The **Community Tips & Stories** page …
=> Feature: Add Community Tips & Stories Page (#356)

pages/WellnessResourceHub.py, requirements.txt
This PR introduces a new **Creative Corner** page to the **Wellness Hub** (`pages/WellnessResourceHub.py`), offering users an interactive space to relax, doodle, and express themselves creatively as part of mindfulness and stress relief activities.
* 🎨 Added **"Creative Corner"** as a new menu item in the sidebar.
* 🎨 Implemented an **interactive drawing canvas** with the following controls:
* **Stroke width** adjustment
* **Stroke color** selection
* **Background color** customization
* 🎨 Integrated **`streamlit-drawable-canvas`** library to power the drawing functionality.
* 🎨 Updated `requirements.txt` to include the new dependency.
* 🎨 Page designed to encourage **creativity and relaxation** within the Wellness Hub.
The **Creative Corner** introduces a playful, mindful, and …
=> Feature: Add Creative Corner with Drawing Canvas (#357)

pages/WellnessResourceHub.py, requirements.txt
This PR introduces a new **Wellness Goal Setting** page in the **Wellness Hub** (`pages/WellnessResourceHub.py`) to help users define, track, and achieve their long-term wellness ambitions.
* 🎯 Added **"Wellness Goal Setting"** as a new menu option in the sidebar.
* 🎯 Users can:
* Add new goals
* Update goal status (Not Started, In Progress, Completed)
* Remove goals when no longer needed
* 🎯 A **progress bar** provides a visual representation of overall completion rate.
* 🎯 Structured to support both **short-term planning** and **long-term growth** within the Wellness Hub.
* **Timeframe**:
* Daily Planner → short-term, daily tasks (e.g., “Drink water,” “Stretch”)
* Goal Setter → long-term ambitions spanning weeks/months (e.g., “Run a 5k,” “Learn a new skill”)
* **Tracking Mechanism**:
* …
=> Feature: Add Wellness Goal Setting Page (#358)

pages/WellnessResourceHub.py, requirements.txt
This PR enhances the **Wellness Goal Setting** page (`pages/WellnessResourceHub.py`) by introducing **target dates**, making long-term planning more structured and effective.
* 📅 **Date Input**: Users can now set a **target completion date** when creating a new goal.
* 📅 **Countdown Display**: Each goal displays its **target date** along with a **countdown of days remaining**.
* 📅 **Overdue Status**: If a goal’s target date passes without being marked as *Completed*, it will automatically show an **Overdue** status.
* 📅 Differentiates the Goal Setter further from the **Daily Planner**, emphasizing **long-term tracking** and accountability.
By adding target dates, users can set **realistic deadlines** for their long-term wellness goals, track progress more effectively, and stay motivated. …
=> Enhancement: Add Target Dates to Wellness Goals (#359)

TalkHeal.py, css/styles.py
added 2 navigation cards for water tracker and wearables in main page
=> added 2 navigation cards for water tracker and wearables in main page
